# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _jamspell
else:
    import _jamspell

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _jamspell.delete_SwigPyIterator

    def value(self):
        return _jamspell.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _jamspell.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _jamspell.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _jamspell.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _jamspell.SwigPyIterator_equal(self, x)

    def copy(self):
        return _jamspell.SwigPyIterator_copy(self)

    def next(self):
        return _jamspell.SwigPyIterator_next(self)

    def __next__(self):
        return _jamspell.SwigPyIterator___next__(self)

    def previous(self):
        return _jamspell.SwigPyIterator_previous(self)

    def advance(self, n):
        return _jamspell.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _jamspell.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _jamspell.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _jamspell.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _jamspell.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _jamspell.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _jamspell.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _jamspell:
_jamspell.SwigPyIterator_swigregister(SwigPyIterator)
class StringVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _jamspell.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _jamspell.StringVector___nonzero__(self)

    def __bool__(self):
        return _jamspell.StringVector___bool__(self)

    def __len__(self):
        return _jamspell.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _jamspell.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _jamspell.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _jamspell.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _jamspell.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _jamspell.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _jamspell.StringVector___setitem__(self, *args)

    def pop(self):
        return _jamspell.StringVector_pop(self)

    def append(self, x):
        return _jamspell.StringVector_append(self, x)

    def empty(self):
        return _jamspell.StringVector_empty(self)

    def size(self):
        return _jamspell.StringVector_size(self)

    def swap(self, v):
        return _jamspell.StringVector_swap(self, v)

    def begin(self):
        return _jamspell.StringVector_begin(self)

    def end(self):
        return _jamspell.StringVector_end(self)

    def rbegin(self):
        return _jamspell.StringVector_rbegin(self)

    def rend(self):
        return _jamspell.StringVector_rend(self)

    def clear(self):
        return _jamspell.StringVector_clear(self)

    def get_allocator(self):
        return _jamspell.StringVector_get_allocator(self)

    def pop_back(self):
        return _jamspell.StringVector_pop_back(self)

    def erase(self, *args):
        return _jamspell.StringVector_erase(self, *args)

    def __init__(self, *args):
        _jamspell.StringVector_swiginit(self, _jamspell.new_StringVector(*args))

    def push_back(self, x):
        return _jamspell.StringVector_push_back(self, x)

    def front(self):
        return _jamspell.StringVector_front(self)

    def back(self):
        return _jamspell.StringVector_back(self)

    def assign(self, n, x):
        return _jamspell.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _jamspell.StringVector_resize(self, *args)

    def insert(self, *args):
        return _jamspell.StringVector_insert(self, *args)

    def reserve(self, n):
        return _jamspell.StringVector_reserve(self, n)

    def capacity(self):
        return _jamspell.StringVector_capacity(self)
    __swig_destroy__ = _jamspell.delete_StringVector

# Register StringVector in _jamspell:
_jamspell.StringVector_swigregister(StringVector)
class PairVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _jamspell.PairVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _jamspell.PairVector___nonzero__(self)

    def __bool__(self):
        return _jamspell.PairVector___bool__(self)

    def __len__(self):
        return _jamspell.PairVector___len__(self)

    def __getslice__(self, i, j):
        return _jamspell.PairVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _jamspell.PairVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _jamspell.PairVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _jamspell.PairVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _jamspell.PairVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _jamspell.PairVector___setitem__(self, *args)

    def pop(self):
        return _jamspell.PairVector_pop(self)

    def append(self, x):
        return _jamspell.PairVector_append(self, x)

    def empty(self):
        return _jamspell.PairVector_empty(self)

    def size(self):
        return _jamspell.PairVector_size(self)

    def swap(self, v):
        return _jamspell.PairVector_swap(self, v)

    def begin(self):
        return _jamspell.PairVector_begin(self)

    def end(self):
        return _jamspell.PairVector_end(self)

    def rbegin(self):
        return _jamspell.PairVector_rbegin(self)

    def rend(self):
        return _jamspell.PairVector_rend(self)

    def clear(self):
        return _jamspell.PairVector_clear(self)

    def get_allocator(self):
        return _jamspell.PairVector_get_allocator(self)

    def pop_back(self):
        return _jamspell.PairVector_pop_back(self)

    def erase(self, *args):
        return _jamspell.PairVector_erase(self, *args)

    def __init__(self, *args):
        _jamspell.PairVector_swiginit(self, _jamspell.new_PairVector(*args))

    def push_back(self, x):
        return _jamspell.PairVector_push_back(self, x)

    def front(self):
        return _jamspell.PairVector_front(self)

    def back(self):
        return _jamspell.PairVector_back(self)

    def assign(self, n, x):
        return _jamspell.PairVector_assign(self, n, x)

    def resize(self, *args):
        return _jamspell.PairVector_resize(self, *args)

    def insert(self, *args):
        return _jamspell.PairVector_insert(self, *args)

    def reserve(self, n):
        return _jamspell.PairVector_reserve(self, n)

    def capacity(self):
        return _jamspell.PairVector_capacity(self)
    __swig_destroy__ = _jamspell.delete_PairVector

# Register PairVector in _jamspell:
_jamspell.PairVector_swigregister(PairVector)
class TSpellCorrector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def LoadLangModel(self, modelFile):
        return _jamspell.TSpellCorrector_LoadLangModel(self, modelFile)

    def TrainLangModel(self, textFile, alphabetFile, modelFile):
        return _jamspell.TSpellCorrector_TrainLangModel(self, textFile, alphabetFile, modelFile)

    def WordIsKnown(self, word):
        return _jamspell.TSpellCorrector_WordIsKnown(self, word)

    def GetCandidatesRawWithScores(self, sentence, position):
        return _jamspell.TSpellCorrector_GetCandidatesRawWithScores(self, sentence, position)

    def GetCandidatesRaw(self, sentence, position):
        return _jamspell.TSpellCorrector_GetCandidatesRaw(self, sentence, position)

    def GetCandidates(self, sentence, position):
        return _jamspell.TSpellCorrector_GetCandidates(self, sentence, position)

    def GetCandidatesWithScores(self, sentence, position):
        return _jamspell.TSpellCorrector_GetCandidatesWithScores(self, sentence, position)

    def FixFragment(self, text):
        return _jamspell.TSpellCorrector_FixFragment(self, text)

    def FixFragmentNormalized(self, text):
        return _jamspell.TSpellCorrector_FixFragmentNormalized(self, text)

    def SetPenalty(self, knownWordsPenalty, unknownWordsPenalty):
        return _jamspell.TSpellCorrector_SetPenalty(self, knownWordsPenalty, unknownWordsPenalty)

    def SetMaxCandidatesToCheck(self, maxCandidatesToCheck):
        return _jamspell.TSpellCorrector_SetMaxCandidatesToCheck(self, maxCandidatesToCheck)

    def GetLangModel(self):
        return _jamspell.TSpellCorrector_GetLangModel(self)

    def __init__(self):
        _jamspell.TSpellCorrector_swiginit(self, _jamspell.new_TSpellCorrector())
    __swig_destroy__ = _jamspell.delete_TSpellCorrector

# Register TSpellCorrector in _jamspell:
_jamspell.TSpellCorrector_swigregister(TSpellCorrector)

